# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cloud Native Blog
email: gumantovan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a Cloud Native Surfer trying to catch some technology waves and learn how to navigate the software industrial revolution. As a Network and Security Engineer, it is my job to learn and understand how automation and programmability is changing Infrastructure. I will be posting what I am learning and my journey to programmability, micro-services and cloud native apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gumantovan
github_username:  gumantov

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
comments:
  - provider: disqus
disqus:
  - shortname: cloudnativeblog
